"""Simulator scenario tests against the real core (Commit 8 §38)."""

from __future__ import annotations

from pathlib import Path

import pytest

from persistence import JsonlSessionEventLog
from simulator.harness import run_scenario
from simulator.scenarios import SCENARIO_BY_NAME, build_all_scenarios
from swimcore.replay import replay_session
from swimcore.session.state import SessionState

pytestmark = pytest.mark.simulator

_ALL_NAMES = [s.name for s in build_all_scenarios()]


def _run(name: str, tmp: Path):  # noqa: ANN202
    scenario = SCENARIO_BY_NAME[name]()
    return run_scenario(scenario, tmp)


@pytest.mark.parametrize("name", _ALL_NAMES)
def test_scenario_reaches_completed(name: str, tmp_path: Path) -> None:
    result = _run(name, tmp_path)
    log = JsonlSessionEventLog(result.journalPath, result.sessionId)
    replay = replay_session(list(log.read_all().events))
    assert replay.state.lifecycleState is SessionState.COMPLETED


@pytest.mark.parametrize("name", _ALL_NAMES)
def test_live_and_replay_agree(name: str, tmp_path: Path) -> None:
    result = _run(name, tmp_path)
    log = JsonlSessionEventLog(result.journalPath, result.sessionId)
    read = log.read_all()
    replay = replay_session(list(read.events))
    # journal line count == batch count; replay last seq == journal last seq
    assert replay.state.lastSeq == read.events[-1].seq
    assert result.journalPath.read_bytes().count(b"\n") == len(read.batches)


@pytest.mark.parametrize("name", _ALL_NAMES)
def test_official_distance_is_pool_multiple(name: str, tmp_path: Path) -> None:
    result = _run(name, tmp_path)
    replay = replay_session(list(result.events))
    st = replay.state
    assert st.officialCompletedDistanceM is not None
    assert st.officialCompletedDistanceM == st.officialCompletedLengthCount * st.poolLengthM


def test_normal_pace_loss_no_stop_pause(tmp_path: Path) -> None:
    result = _run("even-on-plan", tmp_path)
    assert not any("StopPause" in e.type.value for e in result.events)
    replay = replay_session(list(result.events))
    assert replay.state.stoppedDurationMs == 0


def test_positive_fade_is_not_incident(tmp_path: Path) -> None:
    result = _run("positive-fade", tmp_path)
    assert not any("StopPause" in e.type.value for e in result.events)


def test_stop_pause_scenario_has_one_interval(tmp_path: Path) -> None:
    result = _run("stop-pause", tmp_path)
    replay = replay_session(list(result.events))
    st = replay.state
    assert len(st.completedStopPauses) == 1
    assert st.stoppedDurationMs > 0
    assert st.lifecycleState is SessionState.COMPLETED


def test_coach_reset_scenario_swaps_profile(tmp_path: Path) -> None:
    result = _run("coach-continuous-reset", tmp_path)
    assert result.replacementInjected
    applied = [e for e in result.events if e.type.value == "CoachPacingResetApplied"]
    assert len(applied) == 1
    assert applied[0].payload.replacementPaceProfileId is not None
    replay = replay_session(list(result.events))
    assert replay.state.stoppedDurationMs == 0  # reset is not a StopPause


def test_locked_splits_scenario_completes(tmp_path: Path) -> None:
    result = _run("locked-splits", tmp_path)
    replay = replay_session(list(result.events))
    assert replay.state.officialCompletedLengthCount == 4


def test_migrated_legacy_scenario_uses_constant_speed(tmp_path: Path) -> None:
    result = _run("migrated-legacy", tmp_path)
    assert result.provenance.curveRepresentation == "CONSTANT_SPEED"


def test_provenance_is_synthetic(tmp_path: Path) -> None:
    result = _run("even-on-plan", tmp_path)
    prov = result.provenance
    assert prov.usedRealHumanData is False
    assert prov.licenseVerified is False
    assert prov.domain.value == "SYNTHETIC_SIMULATION"


def test_uses_simulated_split_source(tmp_path: Path) -> None:
    result = _run("even-on-plan", tmp_path)
    splits = [e for e in result.events if e.type.value == "SplitRecorded"]
    assert splits
    for e in splits:
        assert e.payload.source.value == "SIMULATED"


def test_golden_journals_match(tmp_path: Path) -> None:
    """The committed simulator goldens equal freshly generated bytes (§32)."""
    mapping = {
        "normal-continuous-session": "even-on-plan",
        "long-stop-continuous-session": "stop-pause",
        "coach-curve-reset-session": "coach-continuous-reset",
    }
    golden_dir = Path(__file__).parent / "goldens"
    for golden, scenario_name in mapping.items():
        result = _run(scenario_name, tmp_path / scenario_name)
        committed = (golden_dir / f"{golden}.jsonl").read_bytes()
        assert result.journalPath.read_bytes() == committed, f"{golden} drifted"
